bulletinboard/urls.py
from django.urls import path, include
from . import views

app_name = 'bulletinboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('init/', views.init, name='init'),
    path('index2/', views.index2, name='index2'), #temporary url
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('board/<int:id>/', views.board, name='board'), # GET request
    path('board/<str:operation>/', views.board, name='board'), # POST request
    path('board/<str:operation>/<int:id>/', views.board, name='board'), # POST request

    path('thread/<int:id>/', views.thread, name='thread'), # GET request
    path('thread2/<int:id>/', views.thread2, name='thread2'), # GET request
    path('thread/<str:operation>/', views.thread, name='thread'), # POST request
    path('thread/<str:operation>/<int:id>', views.thread, name='thread'), # POST request

    path('post/<str:operation>/', views.post, name='post'),

    path('user/<str:username>/', views.user, name='user'),
    path('user/<str:operation>/<str:username>', views.user, name='user'),
]

djangoexam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bulletinboard.urls')),
    path('admin/', admin.site.urls),
    path('bulletinboard/', include('bulletinboard.urls'))
]

bulletinboard/models.py
from django.contrib.auth.models import User, Group
from django.db import models


# Create your models here.

class SiteUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #role = models.ForeignKey(Role, on_delete=models.CASCADE)
    is_banned = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def _check_groups_permissions(self, codename):
        for group in self.user.groups.all():
            for permission in group.permissions.all():

                if permission.codename == codename:
                    return True

        return False

    def can_add_board(self):
        return self._check_groups_permissions('add_board')

    def can_delete_board(self):
        return self._check_groups_permissions('delete_board')

    def can_ban_site_user(self):
        return self._check_groups_permissions('can_ban_site_user')

    def can_unban_site_user(self):
        return self._check_groups_permissions('can_unban_site_user')

    def can_add_thread(self):
        return self._check_groups_permissions('add_thread')

    def can_lock_thread(self):
        return self._check_groups_permissions('can_lock_thread')

    def can_unlock_thread(self):
        return self._check_groups_permissions('can_unlock_thread')

    def can_add_post(self):
        return self._check_groups_permissions('add_post')


class Board(models.Model):
    name = models.CharField(max_length=100)
    creator = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    created_on = models.DateTimeField()
    position = models.PositiveSmallIntegerField(default=0)


class Thread(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    posted_by = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    posted_on = models.DateTimeField()
    is_locked = models.BooleanField(default=False)


class Post(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    message = models.TextField()
    posted_by = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    posted_on = models.DateTimeField()

bulletinboard/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=150)
    email = forms.EmailField()
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=150)
    password = forms.CharField(max_length=100)

class BoardForm(forms.Form):
    name = forms.CharField(max_length=100)
    position = forms.IntegerField()

class ThreadForm(forms.Form):
    title = forms.CharField(max_length=300)

bulletinboard/views.py
from django.contrib.auth.models import User, Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import authenticate

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import models, IntegrityError
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.utils import timezone

from .models import SiteUser, Board, Thread, Post
from .forms import RegisterForm, BoardForm, ThreadForm

# Create your views here.


# temporary function for the new templates
def index2(request):
    boards = Board.objects.order_by('position')
    context = {'boards': boards}
    return render(request, 'bulletinboard/index2.html', context)


# temporary function for the new templates
def thread2(request, id=None):
    threads = Thread.objects.all()
    context = {'threads': threads}
    return render(request, 'bulletinboard/thread2.html', context)


def init(request):

    # add custom user permissions
    content_type = ContentType.objects.get_for_model(SiteUser)
    permission = Permission.objects.create(
        codename='can_ban_site_user',
        name='Can ban site users',
        content_type=content_type,
    )
    permission = Permission.objects.create(
        codename='can_unban_site_user',
        name='Can unban site users',
        content_type=content_type,
    )

    # add custom thread permissions
    content_type = ContentType.objects.get_for_model(Thread)
    permission = Permission.objects.create(
        codename='can_lock_thread',
        name='Can lock threads',
        content_type=content_type,
    )
    permission = Permission.objects.create(
        codename='can_unlock_thread',
        name='Can unlock threads',
        content_type=content_type,
    )

    return HttpResponse('OK')


def index(request):

    context = {}
    site_user = None

    if 'user' in request.session:
        context['session'] = request.session['user']
        site_user = SiteUser.objects.get(user__username=context['session']['username'])
        print(site_user.can_add_board())

    boards = Board.objects.order_by('position')
    boards_list = []

    for board in boards:
        threads_count = board.thread_set.count()
        recent_thread = None
        threads = board.thread_set.all()

        post_count = 0
        for thread in threads:
            count = thread.post_set.count()
            post_count += count

            if count == 0:
                continue

            if recent_thread == None:
                recent_thread = thread
                continue

            if thread.post_set.order_by('-posted_on').first().posted_on > recent_thread.post_set.order_by('-posted_on').first().posted_on:
                recent_thread = thread


        boards_list.append({
            'board': board,
            'threads_count': threads_count,
            'post_count': post_count,
            'recent_thread': recent_thread,
        })


    context['data'] = boards_list
    context['site_user'] = site_user

    return render(request, 'bulletinboard/index.html', {'context': context});


def register(request):

    if request.method == 'GET':
        return render(request, 'bulletinboard/register.html')
    else:

        form = RegisterForm(request.POST)
        context = {}

        if form.is_valid():
            try:
                user = User.objects.create_user(
                    username=form.cleaned_data['username'],
                    first_name=request.POST['first_name'], last_name=request.POST['last_name'],
                    email=request.POST['email'], password=form.cleaned_data['password']
                    )

            except(IntegrityError):

                context['integrity'] = False
                context['data'] = form.cleaned_data
                return render(request, 'bulletinboard/register.html', {'context': context})
            else:
                group = Group.objects.get(name='Poster')
                user.groups.add(group)
                site_user = SiteUser(user=user, is_banned=False)
                site_user.save()
                return HttpResponseRedirect(reverse('bulletinboard:index'))
        else:
            context['form_errors'] = form.errors
            context['data'] = form.cleaned_data,
            return render(request, 'bulletinboard/register.html', {'context': context})


def login(request):

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'],
                password=request.POST['password'])

        if user is not None:
            site_user = SiteUser.objects.get(user=user)

            request.session['user'] = dict()
            request.session['user']['username'] = site_user.user.username
            request.session['user']['email'] = site_user.user.email
            request.session['user']['is_banned'] = site_user.is_banned
            request.session.modified = True

        return HttpResponseRedirect(reverse('bulletinboard:index'))


def logout(request):

    if 'user' in request.session:
        del request.session['user']
        request.session.modified = True

    return HttpResponseRedirect(reverse('bulletinboard:index'))


def board(request, operation=None, id=None):

    if request.method == 'POST':
        site_user = SiteUser.objects.get(user__username=request.session['user']['username'])
        if operation == 'create' and site_user.can_add_board():
            form = BoardForm(request.POST)

            if form.is_valid():
                board = Board(
                    name=request.POST['name'],
                    creator=site_user,
                    created_on=timezone.now(),
                    position=request.POST['position']
                    )

                board.save()

        return HttpResponseRedirect(reverse('bulletinboard:index'))

    else: # GET

        context = {}


        if 'user' in request.session:
            context['session'] = request.session['user']
            site_user = SiteUser.objects.get(user__username=request.session['user']['username'])
            context['site_user'] = site_user

            if operation == 'remove' and site_user.can_delete_board():
                board = Board.objects.get(pk=id)
                board.delete()

                return HttpResponseRedirect(reverse('bulletinboard:index'))

        board = Board.objects.get(pk=id)
        threads = board.thread_set.order_by('-posted_on')

        thread_list = []

        for thread in threads:
            post = thread.post_set.order_by('-posted_on').first()
            thread_list.append({'thread': thread, 'post': post})

        paginator = Paginator(thread_list, 5)

        page = request.GET.get('page')
        page = page if not None else 1
        paginated_thread_list = paginator.get_page(page)

        context['data'] = {
            'board': board,
            'threads_with_recent_post': paginated_thread_list
        }


        return render(request, 'bulletinboard/board.html', {'context': context})


def thread(request, operation=None, id=None):

    if request.method == 'POST':

        site_user = SiteUser.objects.get(user__username=request.session['user']['username'])
        if operation == 'create' and site_user.can_add_thread():
            board = Board.objects.get(pk=request.POST['board'])
            form = ThreadForm(request.POST)

            if form.is_valid():
                thread = Thread(
                    board=board,
                    title=request.POST['title'],
                    posted_by=site_user,
                    posted_on=timezone.now(),
                    is_locked=False
                )
                thread.save()

        return HttpResponseRedirect(reverse('bulletinboard:board', args=(board.id,)))

    else: # GET
        context = {}
        if 'user' in request.session:
            context['session'] = request.session['user']
            site_user = SiteUser.objects.get(user__username=request.session['user']['username'])
            context['site_user'] = site_user

            if operation == 'lock' and site_user.can_lock_thread():

                thread = Thread.objects.get(pk=id)
                thread.is_locked = True
                thread.save()

                return HttpResponseRedirect(reverse('bulletinboard:thread', args=(id,)))

            elif operation == 'unlock' and site_user.can_unlock_thread():

                thread = Thread.objects.get(pk=id)
                thread.is_locked = False
                thread.save()

                return HttpResponseRedirect(reverse('bulletinboard:thread', args=(id,)))


        thread = Thread.objects.get(pk=id)
        posts = thread.post_set.all()

        paginator = Paginator(posts, 5)
        page = request.GET.get('page')
        page = page if page is not None else 1

        paginated_posts = paginator.get_page(page)
        context['data'] = {
            'thread': thread,
            'posts': paginated_posts,
        }


        return render(request, 'bulletinboard/thread.html', {'context': context})


def post(request, operation=None):

    if request.method == 'POST':

        site_user = SiteUser.objects.get(user__username=request.session['user']['username'])
        if operation == 'create' and site_user.can_add_post():

            thread = Thread.objects.get(pk=request.POST['thread'])
            post = Post(thread=thread,
                message=request.POST['message'],
                posted_by=site_user,
                posted_on=timezone.now()
            )
            post.save()

        return HttpResponseRedirect(reverse('bulletinboard:thread', args=(thread.id,)))


def user(request, operation=None, username=None):

    if request.method == 'POST':
        return HttpResponseRedirect(reverse('bulletinboard:index'))
    else: # GET

bulletinboard/templates/bulletinboard/board.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bulletinboard/styles.css' %}">

<div class="">
  <h2>{{ context.data.board.name }}</h2>
  <div class="">
    {% if context.session %}
      {% if context.site_user.can_delete_board %}
        <a href="{% url 'bulletinboard:board' operation='remove' id=context.data.board.id %}">Remove this board</a>
      {% endif %}
      {% if not context.site_user.is_banned %}
        <div class="">
          <form class="" action="{% url 'bulletinboard:thread' operation='create' %}" method="post">
            {% csrf_token %}
            <label for="">Title:
              <input type="text" name="title" value="">
            </label>
            <input type="hidden" name="board" value="{{ context.data.board.id }}">
            <button type="submit" name="submit">Create</button>
          </form>
        </div>
      {% endif %}
    {% endif %}
      <div class="">
        {% for t in context.data.threads_with_recent_post %}
          <div class="thread-item">
            <a href="{% url 'bulletinboard:thread' id=t.thread.id %}">{{ t.thread.title }}</a> {% if t.thread.is_locked == True %}<span>[Locked]</span>{% endif %}
            <br>
            <span>Last reply: {{ t.post.posted_on }}</span> - <span>{{ t.post.posted_by.username }}</span>
          </div>
        {% endfor %}
    </div>
  </div>
  <span>
    {% if context.data.threads_with_recent_post.has_previous %}
      <a href="?page=1">First</a>
      <a href="?page={{ context.data.threads_with_recent_post.previous_page_number }}">Previous</a>
    {% endif %}
    <span>
      Page {{ context.data.threads_with_recent_post.number }} of {{ context.data.threads_with_recent_post.paginator.num_pages }}
    </span>
    {% if context.data.threads_with_recent_post.has_next %}
      <a href="?page={{ context.data.threads_with_recent_post.next_page_number }}">Next</a>
      <a href="?page={{ context.data.threads_with_recent_post.paginator.num_pages }}">Last</a>
    {% endif %}
  </span>
</div>
<a href="{% url 'bulletinboard:index' %}">Go to homepage</a>

bulletinboard/templates/bulletinboard/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bulletinboard/styles.css' %}">

{%if not context.session %}
<div class="">
  <h2>Login</h2>
  <form class="" action="{% url 'bulletinboard:login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:
      <input id="username" type="username" name="username" value="">
    </label>
    <label for="email">Password:
      <input id="password" type="password" name="password" value="">
    </label>

    <button type="submit" name="submit">Login</button>
  </form>
  <a href="{% url 'bulletinboard:register' %}">Register here</a>
</div>
{% else %}
  <a href="{% url 'bulletinboard:logout' %}">Logout</a>
{% endif %}
<div class="">
  <h2>List of Boards</h2>
  <br>
  {% if context.site_user.can_add_board %}
    <form class="" action="{% url 'bulletinboard:board' 'create' %}" method="post">
      {% csrf_token %}
      <label for="board-name">Name:
        <input id="board-name" type="text" name="name" value="">
      </label>
      <label for="board-position">Position:
        <input id="board-postion" type="text" name="position" value="">
      </label>

      <button type="submit" name="submit">Create</button>
    </form>
  {% endif %}

  {% for d in context.data %}
    <div class="board-item">
      <a href="{% url 'bulletinboard:board' d.board.id %}"><h3>{{ d.board.name }}</h3></a>
      <div class="">
        <span>Number of threads: {{ d.threads_count }}</span> | <span>Number of posts: {{ d.post_count }}</span>
        <br>
        <span>Recent thread: {% if d.recent_thread  %} <a href="{% url 'bulletinboard:thread' d.recent_thread.id %}">{{ d.recent_thread.title }}</a> {% else %} <span>No activity yet</span> {% endif %}</span>
      </div>
    </div>
  {% endfor %}
</div>

bulletinboard/templates/bulletinboard/index2.html
{% load static %}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" type="text/css" href="{% static 'bulletinboard/material.css' %}">
<script type="text/javascript" src="{% static 'bulletinboard/material.js' %}">

</script>

<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">Bulletin Board</span>
      <div class="mdl-layout-spacer"></div>
      <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="">Boards</a>
        <a class="mdl-navigation__link" href="">Threads</a>
        <a class="mdl-navigation__link" href="">Login</a>
        <a class="mdl-navigation__link" href="">Register</a>
      </nav>
    </div>
  </header>

  <main class="mdl-layout__content">
    <div class="page-content">
      <div class="mdl-grid">
        {% for board in boards %}
            <div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col">
              <div class="mdl-card_title">
                <h2 class="mdl-card__title-text">{{ board.name }}</h2>
              </div>
              <div class="mdl-card__supporting-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Mauris sagittis pellentesque lacus eleifend lacinia...
              </div>
              <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                  Get Started
                </a>
              </div>
            </div>
        {% endfor %}
      </div>
    </div>
  </main>
</div>

bulletinboard/templates/bulletinboard/register.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bulletinboard/styles.css' %}">

<form class="" action="{% url 'bulletinboard:register' %}" method="post">
  {% csrf_token %}
  <label for="username">Username:
    <input id="username" type="text" name="username" value="{{ context.data.username }}">
    <span class="error">{{ context.form_errors.username.0 }}</span>
    {% if context.integrity == False %}
      <span class="error">username already taken</span>
    {% endif %}
  </label>
  <br>
  <label for="firstname">Firstname:
    <input id="firstname" type="text" name="first_name" value="{{ context.data.first_name }}">
    <span class="error">{{ context.form_errors.first_name.0 }}</span>
  </label>
  <br>
  <label for="lastname">Lastname:
    <input id="lastname" type="text" name="last_name" value="{{ context.data.last_name }}">
    <span class="error">{{ context.form_errors.last_name.0 }}</span>
  </label>
  <br>
  <label for="email">Email:
    <input id="email" type="email" name="email" value="{{ context.data.email }}">
    <span class="error">{{ context.form_errors.email.0 }}</span>
  </label>
  <br>
  <label for="password">Password:
    <input id="password" type="password" name="password" value="">
    <span class="error">{{ context.form_errors.password.0 }}</span>
  </label>
  <br>
  <button type="submit" name="submit">Register</button>
</form>
<a href="{% url 'bulletinboard:index' %}">Go to homepage</a>

bulletinboard/templates/bulletinboard/thread.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bulletinboard/styles.css' %}">

<div class="">
  <h2>{{ context.data.thread.title }} - {{ context.data.thread.board.name }}</h2>

  <div class="">
    {% if context.session %}
      {% if context.site_user.can_lock_thread %}
        {% if context.data.thread.is_locked == False %}
          <a href="{% url 'bulletinboard:thread' operation='lock' id=context.data.thread.id %}">Lock this thread</a>
        {% endif %}
      {% endif %}

      {% if context.site_user.can_unlock_thread %}
        {% if context.data.thread.is_locked == True %}
          <a href="{% url 'bulletinboard:thread' operation='unlock' id=context.data.thread.id %}">Unlock this thread</a>
        {% endif %}
      {% endif %}
      {% if context.data.thread.is_locked == False and context.site_user.is_banned == False %}
        <div class="">
          <form class="" action="{% url 'bulletinboard:post' 'create' %}" method="post">
            {% csrf_token %}
            <textarea name="message" rows="8" cols="50"></textarea>
            <br>
            <input type="hidden" name="thread" value="{{ context.data.thread.id }}">
            <button type="submit" name="submit">Post</button>
          </form>
        </div>
      {% endif %}
    {% endif %}
    <div class="">
      {% for post in context.data.posts %}
        <div class="post-item">
          <span> <a href="{% url 'bulletinboard:user' username=post.posted_by.user.username %}">{{ post.posted_by.user.username }}</a>( {{ post.posted_by.user.email }} )</span> - <span>{{ post.posted_on }}</span>
          <p>
            {{ post.message }}
          </p>
        </div>
      {% endfor %}
    </div>
  </div>
  <span>
    {% if context.data.posts.has_previous %}
      <a href="?page=1">First</a>
      <a href="?page={{ context.data.posts.previous_page_number }}">Previous</a>
    {% endif %}
    <span>
      Page {{ context.data.posts.number }} of {{ context.data.posts.paginator.num_pages }}
    </span>
    {% if context.data.posts.has_next %}
      <a href="?page={{ context.data.posts.next_page_number }}">Next</a>
      <a href="?page={{ context.data.posts.paginator.num_pages }}">Last</a>
    {% endif %}
  </span>
</div>
<a href="{% url 'bulletinboard:index' %}">Go to homepage</a>

bulletinboard/templates/bulletinboard/thread2.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bulletinboard/styles.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" type="text/css" href="{% static 'bulletinboard/material.css' %}">

<script type="text/javascript" src="{% static 'bulletinboard/material.js' %}">

</script>

<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">Bulletin Board</span>
      <div class="mdl-layout-spacer"></div>
      <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="">Boards</a>
        <a class="mdl-navigation__link" href="">Threads</a>
        <a class="mdl-navigation__link" href="">Login</a>
        <a class="mdl-navigation__link" href="">Register</a>
      </nav>
    </div>
  </header>

  <main class="mdl-layout__content">
    <div class="page-content">
      <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--2-col">

        </div>
        <div class="threads-content mdl-cell mdl-cell--5-col">
          {%  for thread in threads %}
            <div class="thread-card mdl-card mdl-shadow--2dp">
              <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">{{ thread.title }}</h2>
                <span class="mdl-chip">
                  <span class="mdl-chip__text">{{ thread.board.name }}</span>
                </span>
              </div>
            </div>
          {% endfor %}
        </div>
        <div class="sidebar-content mdl-cell mdl-cell--2-col">

        </div>
        <div class="sidebar-content mdl-cell mdl-cell--3-col">

        </div>
      </div>
    </div>
  </main>
</div>

bulletinboard/templates/bulletinboard/user.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bulletinboard/styles.css' %}">
<div class="">
  <h2>{{ context.user_profile.user.username }}</h2>
  {% if context.site_user.can_ban_site_user %}
    {% if not context.site_user.is_banned  %}
      <a href="{% url 'bulletinboard:user' operation='ban' username=context.user_profile.user.username %}">Ban this account</a>
    {% endif %}
  {% endif %}

  {% if context.site_user.can_unban_site_user %}
    {% if context.site_user.is_banned %}
      <a href="{% url 'bulletinboard:user' operation='unban' username=context.user_profile.user.username %}">Unban this account</a>
    {% endif %}
  {% endif %}
  <div class="">
    {% for post in context.data.posts %}
      <div class="post-item">
        <span>{{ post.posted_on }}</span>
        <p>
          {{ post.message }}
        </p>
      </div>
    {% endfor %}
  </div>
  <span>
    {% if context.data.posts.has_previous %}
      <a href="?page=1">First</a>
      <a href="?page={{ context.data.posts.previous_page_number }}">Previous</a>
    {% endif %}
    <span>
      Page {{ context.data.posts.number }} of {{ context.data.posts.paginator.num_pages }}
    </span>
    {% if context.data.posts.has_next %}
      <a href="?page={{ context.data.posts.next_page_number }}">Next</a>
      <a href="?page={{ context.data.posts.paginator.num_pages }}">Last</a>
    {% endif %}
  </span>
</div>
<a href="{% url 'bulletinboard:index' %}">Go to homepage</a>